version: 2
jobs:
  build:
    docker:
      - image: hashicorp/terraform:0.11.1
    steps:
      - checkout
      - run: mkdir -p workdir
      - run: echo "terraform init"
      - run: echo "terraform plan -var profile=test -out=workdir/terraform.tfplan"
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: workdir
          # Must be relative path from root
          paths:
            - terraform.tfplan
