version: 2
jobs:
  build:
    docker:
      - image: hashicorp/terraform:0.11.1
    steps:
      - checkout
      - run: apk add --update py-pip && pip install awscli
      - run: aws --region=ap-northeast-1 s3 cp ${S3_CREDENTIALS_URL} ~/.aws/credentials && chmod 600 ~/.aws/credentials

  test:
    docker:
      - image: hashicorp/terraform:0.11.1
    steps:
      - checkout
      - run: cd terraform/awsomeservice && terraform init
      - run: cd terraform/awsomeservice && terraform workspace select production
      - run: cd terraform/awsomeservice && terraform plan -var profile=default

  deploy:
    docker:
      - image: hashicorp/terraform:0.11.1
    branches:
      only:
        - master
    steps:
      - run: echo 'cd terraform/awsomeservice && terraform init -reconfigure -backend-config="profile=deploy"'
      - run: echo 'cd terraform/awsomeservice && terraform workspace select production'
      - run: echo 'cd terraform/awsomeservice && terraform plan -var profile=deploy -out deployment.tfplan'

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
  build-test-deploy:
    branches:
      only:
        - master
    jobs:
      - build
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - test
      - deploy:
          requires:
            - hold

