version: 2
jobs:
  build:
    docker:
      - image: hashicorp/terraform:0.11.1
    steps:
      - checkout
      - run: apk add --update py-pip && pip install awscli
      - run: aws --region=ap-northeast-1 s3 cp ${S3_CREDENTIALS_URL} ~/.aws/credentials && chmod 600 ~/.aws/credentials
      - run: cd terraform/awsomeservice && terraform init
      - run: cd terraform/awsomeservice && terraform workspace select production

  test:
    docker:
      - image: hashicorp/terraform:0.11.1
    steps:
      - checkout
      - run: mkdir -p $CIRCLE_TEST_REPORTS/terraform
      - run: cd terraform/awsomeservice && terraform plan -var profile=default > $CIRCLE_TEST_REPORTS/plan.txt

deployment:
  terraform-apply:
    branch: master
    commands:
      - cd terraform/awsomeservice && terraform init -reconfigure -backend-config="profile=deploy"
      - cd terraform/awsomeservice && terraform workspace select production
      - cd terraform/awsomeservice && terraform plan -var profile=deploy -out deployment.tfplan

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
        requires:
          - build

