version: 2
jobs:
  build:
    docker:
      - image: hashicorp/terraform:0.11.1
    steps:
      - checkout
      - run: apk add --update py-pip && pip install awscli
      - run: aws --region=ap-northeast-1 s3 cp ${S3_CREDENTIALS_URL} ~/.aws/credentials && chmod 600 ~/.aws/credentials
      - run: cd terraform/awsomeservice && terraform init
      - run: cd terraform/awsomeservice && terraform workspace select development
      - run: cd terraform/awsomeservice && terraform plan -var profile=default -out terraform.tfplan
